[package]
name = "cloudflare-updater"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.14.0"
reqwest = { version = "0.12.8", features = ["blocking", "json"] }
simple-error = "0.1.9"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
